env = Environment(CC = "g++", CCFLAGS = "-Wall -std=c++11 -O3")
src = [
    "perfTest.cpp",
    "FnPtrBlockNode/node.cpp",
    "SwitchBlockNode/node.cpp",
    "FnPtrSingleNode/node.cpp"
]
env.Program("perfTest", src,  LIBS = [])

